build: off
platform: x64
image: Visual Studio 2015

install:
  - nuget install zlib
  - mkdir build
  - cd build
  - dir "C:\Program Files (x86)"
  - dir "C:\Program Files (x86)\microsoft visual studio 14.0"
  - dir "C:\Program Files (x86)\microsoft visual studio 14.0\Common7\Tools"
  - call "C:\Program Files (x86)\microsoft visual studio 14.0\Common7\Tools\VC\vcvarsall.bat" %platform%
  - cmake -G "NMake Makefiles" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ..
  - nmake
  - nmake test
  - nmake install

#test_script:
#  - conda build recipe --quiet
#deploy_script:
#  - cmd: upload_or_check_non_existence .\recipe conda-forge --channel=main
