build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        ARCH: x64
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        ARCH: x64

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install-zlib.bat')" && install-zlib.bat
    - set PATH=%programfiles%\zlib\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zstd.install/master/install.bat', 'install-zstd.bat')" && call install-zstd.bat
    - set PATH=%programfiles%\zstd\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/almosthere/master/install.bat', 'install.bat')" && call install.bat
    - set PATH=%programfiles%\athr\bin;%PATH%
    - cmake ..
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_GENERATOR_PLATFORM=%ARCH%
        -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%
    - cmake --build . --config Release --target install
    - ctest -V --output-on-failure -C Release
    - appveyor DownloadFile https://raw.githubusercontent.com/limix/bgen/master/install.bat && install.bat

test_script:
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\bgen.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\bin\bgen.dll exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\bgen_static.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\include\bgen.h exit 1
