build: off
platform: x64
image: Visual Studio 2015

install:
  - mkdir build
  - cd build
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcvarsall.bat" amd64
  - cmake -G "NMake Makefiles" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ..
  - nmake
  - nmake test
  - nmake install

#test_script:
#  - conda build recipe --quiet
#deploy_script:
#  - cmd: upload_or_check_non_existence .\recipe conda-forge --channel=main
