build: off
platform: x64
image: Visual Studio 2015
environment:
  PLATFORM: "x64"
  CONFIGURATION: "Release"

build_script:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - choco install cmake
  - set PATH=C:\Program Files\CMake\bin;%PATH%
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://gist.githubusercontent.com/Horta/18a6bda81f254d6a9f8f61e82101b66b/raw/8d851f0a2aa9449336eff463b48924f3da76c2be/install-zlib.bat', 'install-zlib.bat')" && .\install-zlib.bat
  - type install.log
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://gist.githubusercontent.com/Horta/3691adb8790e0d6358a54a00ffe4edd3/raw/f6b57c6ef0df967fc8d0b2ec5e3ac80c631972c0/install-zstd.bat', 'install-zstd.bat')" && .\install-zstd.bat
  - type install.log
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/progressbar/master/install.bat', 'install.bat')" && .\install.bat
  - type install.log
  - mkdir build && cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER% ..
  - cmake --build . --config %CONFIGURATION% --target install
  - if exist %CONFIGURATION% copy %CONFIGURATION%\*.* . /Y
  - ctest -V --output-on-failure -C %CONFIGURATION%
  - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\bgen.lib exit 1
  - if NOT exist %APPVEYOR_BUILD_FOLDER%\bin\bgen.dll exit 1
  - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\bgen_static.lib exit 1
